Add Kafka Python Tutorial
TheDataMuni/datamuni pull request #3
Opened 2020-12-06 16:27 UTC by rohit-anilkumar

Tutorial on implementing a kafka producer using Kafka Python package. The intended user should have a basic understanding of Kafka terminologies

2020-12-07 13:18 UTC, rohit-anilkumar commented
@abhishekkrthakur Could you verify this PR

2020-12-07 16:41 UTC, abhishekkrthakur commented
@rohit-anilkumar please dont worry. it will be reviewed.

2020-12-13 08:44 UTC, abhishekkrthakur requested changes
Added a few comments, overall it looks okay. it would also be nice if you can add some examples of how the data will look like. you can also copy-paste your markdown here to know how it will render on the website: https://datamuni.com/renderer

2020-12-13 08:44 UTC, abhishekkrthakur commented on users/rohit-anilkumar/ARTICLE.md
> +### Disclaimer: This article is not an introduction to Apache Kafka and expects the reader to have some basic understanding of the various terminologies related to Kafka.
put disclaimer after title

2020-12-13 08:44 UTC, abhishekkrthakur commented on users/rohit-anilkumar/ARTICLE.md
> +### Implementing an Apache Kafka Producer in Python for realtime BBC News Feed
make title as heading by using one #

2020-12-13 08:44 UTC, abhishekkrthakur commented on users/rohit-anilkumar/ARTICLE.md
> +The code above is pretty much self explanatory, but in case you need further clarifications reach out at rohitanil93@gmail.com. If the PR gets approved, I will soon write an article on implementing a
please remove this line: If the PR gets approved, I will soon write an article on implementing a Kafka Consumer which will read news from the broker and classify the news feed into various categories using machine learning.

2020-12-13 08:44 UTC, abhishekkrthakur commented on users/rohit-anilkumar/title
> +
remove extra lines

2020-12-15 19:27 UTC, abhishekkrthakur commented
@rohit-anilkumar  ohh, something major is wrong :) you are missing folder for your article. so no one will be able to access it. if you fix this, we merge it. Your ARTICLE.md and title should be in a folder. Maybe lets call it: `implementing-apache-kafka-producer-python` :) 


Please see:

```
- Inside your username, create a folder that will be the URL title. e.g. `supervised-vs-unsupervised-learning`. Please note that this name can only contain hyphens and english alphabets.
- Write your article in `ARTICLE.md` inside this folder.
- Add assets, e.g. any images to `assets` inside this folder.
- Create a file called `title` (without extensions) and add title of your article. It is the name that will be used everywhere in the website. Note that your `ARTICLE.md` must also have a title. :

Final structure should look like this:

    datamuni
        |-- users
            |-- username
            |   |-- PROFILE.md
            |   |-- article-example-1
            |   |   |-- ARTICLE.md
            |   |   |-- title
            |   |   `-- assets
            |   |       |-- 1.png
            |   |       |-- 2.png
            |   |       `-- 3.png
            |	|-- article-example-2
            |	|   |-- ARTICLE.md
```

2020-12-16 20:10 UTC, rohit-anilkumar commented
@abhishekkrthakur Requested changes have been made! :)

2020-12-17 03:42 UTC, merged