Handful bricks
TheDataMuni/datamuni pull request #6
Opened 2020-12-06 22:58 UTC by joatom

Initial version of "A handful bricks - from SQL to Pandas."

Hello Abhishek,
I hope this article is not to basic / nonsense. 
Regards, Johannes

2020-12-07 10:44 UTC, abhishekkrthakur requested changes

2020-12-07 10:44 UTC, abhishekkrthakur commented on users/joatom/a-handful-of-bricks-from-sql-to-pandas/.ipynb_checkpoints/ARTICLE-checkpoint.md
> +# Table of contents
remove this file

2020-12-07 10:44 UTC, abhishekkrthakur commented on users/joatom/a-handful-of-bricks-from-sql-to-pandas/ARTICLE.md
> +# Table of contents
although, we do have title file, you still need to add title here and please convert other titles to subtitles by using "##"

2020-12-07 10:44 UTC, abhishekkrthakur commented on users/joatom/a-handful-of-bricks-from-sql-to-pandas/assets/Readme.md
> +# References
We dont need it. Maybe add it at the end of the article and remove this file

2020-12-07 10:44 UTC, abhishekkrthakur commented on users/joatom/gihub_username
> +joatom
dont need this file. :) please remove it

2020-12-07 10:45 UTC, abhishekkrthakur commented
> I hope this article is not to basic / nonsense.
haha...its pretty good! Added a few comments that need to be fixed before merging :)

2020-12-07 19:28 UTC, joatom commented
do you mind to add `.ipynb_checkpoints` to the central .gitignore? or am I allowed to put my customized .gitignore to my users folder?

2020-12-08 10:53 UTC, abhishekkrthakur commented
Feel free to add it to central .gitignore :)

2020-12-08 10:54 UTC, merged

2020-12-08 10:55 UTC, abhishekkrthakur commented
merged. ill add it to central .gitignore